main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Publications
    url: '#publications'
    weight: 20
  - name: Experience
    url: '#experience'
    weight: 30
  - name: Awards
    url: '#accomplishments'
    weight: 40
  
